spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 611226492503-pilpstdhkdemun0fonqmcmap24esob06.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile